### ISSUE TITLE
Option to run vault as a linux user

### ISSUE THREAD

**Issue by ssurenr** [cloudfoundry-community/vault-boshrelease#46]
Vault process is now invoked by root. However, administrator may need to execute vault as normal user when writing to NFS backend. It also increases security overall.

**Comment by jhunt** [comment]
Now that I've figured out how to setcap properly for Vault, we can just move over to running as the vcap user, wholesale.

**Comment by ssurenr** [comment]
Agree. vcap is just fine.

**Comment by jhunt** [comment]
The safe-boshrelease (https://github.com/cloudfoundry-community/safe-boshrelease) does this, btw.

**Comment by lrstanley** [comment]
I see this was just closed out.. has any change been made to allow support for running as the vcap user? I see a handful of chown's are made to change permissions to vcap, but vault still runs as the root user, so any files created by vault are still `root:root`.

Running as the root user is a bit of an issue as well, because enabling things like vaults audit log files, other releases cannot read the logs files (e.g. like using syslog-release to forward logs), amongst other things.

**Comment by jhunt** [comment]
@lrstanley is the safe-boshrelease (https://github.com/cloudfoundry-community/safe-boshrelease) not sufficient?  It runs as vcap (https://github.com/cloudfoundry-community/safe-boshrelease/blob/master/jobs/vault/templates/bin/vault#L38-L40)

**Comment by lrstanley** [comment]
Well, there is a reason that vault-boshrelease exists, along side safe-boshrelease, no?

**Comment by jhunt** [comment]
The vault-boshrelease is for experimentation.  safe-boshrelease is a Vault for production.

**Comment by ssurenr** [comment]
[I wanted something simpler and more opinionated.](https://github.com/cloudfoundry-community/safe-boshrelease#but-why-not-use-the-vault-bosh-release) 😃 
We love `vault.config` in vault bosh release. Will you accept a PR fixing this?

**Comment by jhunt** [comment]
Sure
