### ISSUE TITLE
Upgrade to vault 1.4.2

### ISSUE THREAD

**Issue by Rukenshia** [cloudfoundry-community/vault-boshrelease#80]
Hi there,

We're using this bosh release and would like to upgrade to the most recent version of vault. Is this project still maintained? I don't have any experience with bosh releases myself, so I am a bit lost with this.

Thanks a bunch!

**Comment by jhunt** [comment]
We can update this BOSH release if you find value in it; but I would first ask if you've looked at something like [Containers BOSH Release](https://github.com/jhunt/containers-boshrelease), which would let you control the version of Vault you are deploying via the BOSH manifest, instead of via the release.

There's an example containerized Vault deployment here: https://github.com/jhunt/containers-boshrelease/blob/master/manifests/vault.yml, and while it is a single node file-backed Vault, you should be able to adapt the configuration according to your needs (i.e. backend storage system).

**Comment by Rukenshia** [comment]
@jhunt thanks! I'll try looking into the containerised deployment, but at the moment we're running a pretty old vault release and want to upgrade to the newest possible version without having to change the infrastructure too much. We have a big data migration ahead of us, so if you could update the release to 1.4.2 that'd be really awesome.

For the future, are there any instructions on how to update the release (and test it / make sure it works properly)? I have never created a bosh release before, so I hope that for the future I could also contribute this.

Cheers,

**Comment by jhunt** [comment]
As an aside, you can use the containers BOSH release to replace your current build, without changing versions (just run the older version of the docker image), and then walk your way forward through whatever intervening versions you want.  As-is, when this BOSH release gets an update, it's going to go straight to 1.4.2.

**Comment by jhunt** [comment]
Available in v1.1.6 of this BOSH release: https://github.com/cloudfoundry-community/vault-boshrelease/releases/tag/v1.1.6

**Comment by Rukenshia** [comment]
Thanks a lot, really appreciate it!
